default_stages: [ pre-commit ]
minimum_pre_commit_version: 2.10.1

repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Run autoflake
        description: Removes unused imports from python scripts
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-all-unused-imports ]

      - id: flake8
        name: Run flake8
        entry: python -m flake8 --ignore=E501
        language: system
        types: [ python ]