from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '439af53e794d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('task_name', sa.String(), nullable=True),
                    sa.Column('task_descriptions', sa.String(), nullable=True),
                    sa.Column('status',
                              sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='taskstatus', native_enum=False),
                              nullable=False),
                    sa.Column('priority', sa.Enum('LOW', 'MIDDLE', 'HIGH', name='taskpriority', native_enum=False),
                              nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('creator_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['creator_id'], ['Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks')
    op.drop_table('Users')
    # ### end Alembic commands ###
